# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9022eaf953d682613749f3d7d14fd1a91b88ba69d377c504cbab356ee62058dd05bad68e2867ad7a105759b94efc84ae30f71cba699ae72f20a1753dd22d6a5

test:
  secret_key_base: 4ea6373f06eb279182dfcd1e5878d8680a38e00c25b3c49680ba41dae6987eaa79831cf3b41223d1f5e9afdb418c30b91eda3e5e030e84ad5178301a43537453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
